<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_5e2d458fbce1a',
    'title' => '[BLOCK] Facebook Page Feed',
    'fields' => array(
        array(
            'key' => 'field_5e2d458fc136a',
            'label' => 'Facebook Page Feed',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e2d458fc1718',
            'label' => 'Section Properties',
            'name' => 'sec_prop',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e2474966be8b',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e2d4a44dd62f',
            'label' => 'Facebook Page Title',
            'name' => 'facebook_page_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Mediterranean Academy of Classical Dressage',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5e2d46cf38ca5',
            'label' => 'Facebook Page Link',
            'name' => 'facebook_page_link',
            'type' => 'url',
            'instructions' => 'The URL of the Facebook Page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'https://www.facebook.com/MaocdDotCom/',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5e2d46e238ca6',
            'label' => 'Width',
            'name' => 'width',
            'type' => 'number',
            'instructions' => 'The pixel width of the plugin. Min. is 180 & Max. is 500.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 340,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 180,
            'max' => 500,
            'step' => 1,
        ),
        array(
            'key' => 'field_5e2d471438ca7',
            'label' => 'Height',
            'name' => 'height',
            'type' => 'number',
            'instructions' => 'The pixel height of the plugin. Min. is 70.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 500,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 70,
            'max' => '',
            'step' => 1,
        ),
        array(
            'key' => 'field_5e2d474038ca8',
            'label' => 'Tabs to show',
            'name' => 'tabs_to_show',
            'type' => 'select',
            'instructions' => 'Tabs to render i.e. timeline, events, messages. Use a comma-separated list to add multiple tabs, i.e. timeline, events.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'timeline' => 'Timeline',
                'events' => 'Events',
                'messages' => 'Messages',
            ),
            'default_value' => array(
                0 => 'timeline',
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5e2d479938ca9',
            'label' => 'Hide Cover',
            'name' => 'hide_cover',
            'type' => 'true_false',
            'instructions' => 'Hide cover photo in the header?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e2d47f238caa',
            'label' => 'Show Facepile',
            'name' => 'show_facepile',
            'type' => 'true_false',
            'instructions' => 'Show profile photos when friends like this.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e2d481538cab',
            'label' => 'Hide CTA',
            'name' => 'hide_cta',
            'type' => 'true_false',
            'instructions' => 'Hide the custom call to action button (if available).',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e2d482738cac',
            'label' => 'Small header',
            'name' => 'small_header',
            'type' => 'true_false',
            'instructions' => 'Use the small header instead.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e2d483838cad',
            'label' => 'Adapt container width',
            'name' => 'adapt_container_width',
            'type' => 'true_false',
            'instructions' => 'Try to fit inside the container width.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e2d458fc1afb',
            'label' => 'Facebook Page Feed - END',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/facebook-page-feed',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e2d727fc68d5',
    'title' => '[BLOCK] Gallery',
    'fields' => array(
        array(
            'key' => 'field_5e2d727fcb709',
            'label' => 'Gallery',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e2d727fcbaed',
            'label' => 'Section Properties',
            'name' => 'sec_prop',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e2474966be8b',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e2d72955c6ef',
            'label' => 'Image Gallery',
            'name' => 'image_gallery',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'insert' => 'append',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5e2d727fcbec7',
            'label' => 'Gallery - END',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/image-gallery',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e247517b8056',
    'title' => '[BLOCK] Hero Images',
    'fields' => array(
        array(
            'key' => 'field_5e247517be42c',
            'label' => 'Hero Images',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e247517be807',
            'label' => 'Section Properties',
            'name' => 'sec_prop',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e2474966be8b',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e247570a7c44',
            'label' => 'Slides',
            'name' => 'slides',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_5e2475ada7c46',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Slide',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e247583a7c45',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium_large',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5e2475ada7c46',
                    'label' => 'Slide Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5e2475f0a7c47',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5e2475faa7c48',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                ),
            ),
        ),
        array(
            'key' => 'field_5e247517bebd3',
            'label' => 'Hero Images - END',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/hero-images',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e3b0c8d890c6',
    'title' => '[BLOCK] Latest Posts',
    'fields' => array(
        array(
            'key' => 'field_5e3b0c8d8db58',
            'label' => 'Latest Posts - Start',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e3b0c8d8df39',
            'label' => 'Section Properties',
            'name' => 'sec_prop',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e2474966be8b',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e3b12c24dc48',
            'label' => 'Title',
            'name' => 'section_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Latest Posts',
            'placeholder' => 'e.g. Latest Posts',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5e3b0d2b869a2',
            'label' => 'Number of posts to display',
            'name' => 'number_of_posts_to_display',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 1,
            'max' => 4,
            'step' => 1,
        ),
        array(
            'key' => 'field_5e3b237391ffe',
            'label' => 'Background Image',
            'name' => 'image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 1920,
            'min_height' => 550,
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpeg,jpg,png',
        ),
        array(
            'key' => 'field_5e3b0c8d8e357',
            'label' => 'Latest Posts - END',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/latest-posts',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e3052156702d',
    'title' => '[BLOCK] Products Slider',
    'fields' => array(
        array(
            'key' => 'field_5e3052156b88d',
            'label' => 'Products Slider - Start',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e3052156bc70',
            'label' => 'Section Properties',
            'name' => 'sec_prop',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e2474966be8b',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e3052cab077b',
            'label' => 'Section Title',
            'name' => 'section_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Latest Products',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5e30526ab077a',
            'label' => 'Select products',
            'name' => 'select_latest',
            'type' => 'button_group',
            'instructions' => 'If <b>latest</b> is chosen, no further action is required.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'latest' => 'Latest Products',
                'manual' => 'Select Manually',
            ),
            'allow_null' => 0,
            'default_value' => 'latest',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_5e305a61d71ec',
            'label' => 'Limit products to',
            'name' => 'limit_products_to',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5e30526ab077a',
                        'operator' => '==',
                        'value' => 'latest',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 20,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_5e30530ab077c',
            'label' => 'Choose products manually',
            'name' => 'chosen_products',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_5e30526ab077a',
                        'operator' => '==',
                        'value' => 'manual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'product',
            ),
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'taxonomy',
            ),
            'elements' => array(
                0 => 'featured_image',
            ),
            'min' => 1,
            'max' => '',
            'return_format' => 'id',
        ),
        array(
            'key' => 'field_5e3052156c040',
            'label' => 'Products Slider - End',
            'name' => '',
            'type' => 'accordion',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'open' => 0,
            'multi_expand' => 0,
            'endpoint' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/products-slider',
            ),
        ),
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'product',
            ),
        ),
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e2474966be8b',
    'title' => '[CLONE] Section Properties',
    'fields' => array(
        array(
            'key' => 'field_5e2474a3ae1d5',
            'label' => 'Active',
            'name' => 'active',
            'type' => 'true_false',
            'instructions' => 'Deactivating this block allows you to remove it from the front end without losing its data.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => false,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e23746456a60',
    'title' => '[OPTIONS] Site Settings',
    'fields' => array(
        array(
            'key' => 'field_5e237474ff0dd',
            'label' => 'Social Media',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e23747dff0de',
            'label' => 'Social Media',
            'name' => 'social_media',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e07dd1c4cd77',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
        array(
            'key' => 'field_5e243cbc12fb5',
            'label' => 'Contact Details',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5e243cc512fb6',
            'label' => 'Contact Details',
            'name' => 'contact_details',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'group_5e243bbd9ae80',
            ),
            'display' => 'group',
            'layout' => 'block',
            'prefix_label' => 1,
            'prefix_name' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'site-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e24855b8cd5c',
    'title' => '[PAGE] Page Options',
    'fields' => array(
        array(
            'key' => 'field_5e24856fb35ac',
            'label' => 'Display page title?',
            'name' => 'display_page_title',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5e24857bb35ad',
            'label' => 'Full width?',
            'name' => 'full_width',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e369c706112a',
    'title' => '[WIDGET] Custom Latest Posts',
    'fields' => array(
        array(
            'key' => 'field_5e369c81d8a21',
            'label' => 'Number of Latest Posts',
            'name' => 'number_of_latest_posts',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 3,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'widget',
                'operator' => '==',
                'value' => 'custom_latest_posts',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5de125948299e',
    'title' => '[WIDGET] Footer Navigation Menus',
    'fields' => array(
        array(
            'key' => 'field_5de125d10757f',
            'label' => 'Title Link',
            'name' => 'title_link',
            'type' => 'page_link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'allow_null' => 1,
            'allow_archives' => 1,
            'multiple' => 0,
        ),
        array(
            'key' => 'field_5de125e907580',
            'label' => 'Pages/Posts/Other',
            'name' => 'pages',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => '',
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'post_type',
                2 => 'taxonomy',
            ),
            'elements' => '',
            'min' => '',
            'max' => '',
            'return_format' => 'object',
        ),
        array(
            'key' => 'field_5dee024ac8963',
            'label' => 'Shop Categories',
            'name' => 'shop_categories',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'product_cat',
            'field_type' => 'checkbox',
            'add_term' => 0,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'object',
            'multiple' => 0,
            'allow_null' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'widget',
                'operator' => '==',
                'value' => 'footer_navigation_menus_widget',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e243bbd9ae80',
    'title' => 'Contact Details',
    'fields' => array(
        array(
            'key' => 'field_5e243bc8570ae',
            'label' => 'Phone Numbers',
            'name' => 'phone_numbers',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Number',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e243c49570af',
                    'label' => 'Type',
                    'name' => 'type',
                    'type' => 'button_group',
                    'instructions' => 'Blue = Active;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'fa-phone' => 'Landline',
                        'fa-mobile-alt' => 'Mobile',
                    ),
                    'allow_null' => 0,
                    'default_value' => 'mobile',
                    'layout' => 'horizontal',
                    'return_format' => 'array',
                ),
                array(
                    'key' => 'field_5e243c91570b0',
                    'label' => 'Country Code',
                    'name' => 'cc',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 356,
                    'placeholder' => '',
                    'prepend' => '+',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5e243ca8570b1',
                    'label' => 'Number',
                    'name' => 'number',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5e243d7ce41a0',
            'label' => 'Emails',
            'name' => 'emails',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Email',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e243d7ce41a3',
                    'label' => 'Email',
                    'name' => 'email',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_5e243da230cfd',
            'label' => 'Location Latitude',
            'name' => 'location_latitude',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_5e243e0f30cfe',
            'label' => 'Location Longitude',
            'name' => 'location_longitude',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'site-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => false,
    'description' => '',
));

acf_add_local_field_group(array(
    'key' => 'group_5e07dd1c4cd77',
    'title' => 'Social Icons',
    'fields' => array(
        array(
            'key' => 'field_5e23730a2bbaf',
            'label' => 'Social Icons',
            'name' => 'social_icons',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_5e23731e2bbb0',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Social Media',
            'sub_fields' => array(
                array(
                    'key' => 'field_5e23731e2bbb0',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'facebook-f' => 'Facebook',
                        'twitter' => 'Twitter',
                        'linkedin-in' => 'Linked-In',
                        'instagram' => 'Instagram',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'array',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5e2374442bbb1',
                    'label' => 'Url',
                    'name' => 'url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'post',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => false,
    'description' => '',
));

endif;
